pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "Building ..."
            }
        }
    }
    post {
        always {
            echo "abnc"
            
           // def response = httpRequest consoleLogResponseBody: true, contentType: 'APPLICATION_JSON', httpMode: 'POST', ignoreSslErrors: true, url: 'https://dev39754.service-now.com/api/190726/snow_jenkins'
           httpRequest consoleLogResponseBody: true, contentType: 'APPLICATION_JSON', httpMode: 'POST', ignoreSslErrors: true, url: 'https://dev39754.service-now.com/api/190726/snow_jenkins?status=Failuer&request_item_number="${params.request_item_number}"&job_name="${JOB_NAME}"&build_number=23' 
            
        }
        failure {
            echo "Pqr"
        }
    }
}
